royerlab/aydin

aydin/gui/tabs/qt/summary.py, docs/source/index.rst
- initial commit, implemented on gui
=> adding links across docs gui and repository

setup.cfg
This PR upgrades the required importlib-metadata version to 4.10.0
=> importlib-metadata version upgraded

aydin/it/transforms/attenuation.py, aydin/it/transforms/base.py, aydin/it/transforms/deskew.py, aydin/it/transforms/fixedpattern.py, aydin/it/transforms/highpass.py, aydin/it/transforms/histogram.py, aydin/it/transforms/motion.py, aydin/it/transforms/padding.py, aydin/it/transforms/periodic.py, aydin/it/transforms/range.py, aydin/it/transforms/salt_pepper.py, aydin/it/transforms/variance_stabilisation.py
This PR brings back the `numpy.typing.ArrayLike` type annotations to `aydin.it.transforms.*` as right now we can depend on a more recent version of numpy.
=> Refactor: bringing back ArrayLike type annotations to it.transforms

aydin/gui/_qt/transforms_tab_widget.py
This PR basically hides the advanced processing tabs instead of just disabling them(current behavior). That's it.
=> GUI: Hiding advanced processing tabs when basic mode is active

aydin/cli/cli.py, aydin/gui/main_page.py, aydin/restoration/denoise/noise2selfcnn.py, aydin/restoration/denoise/util/denoise_utils.py
This PR introduces changes to include processing tab related details in saved .zip file. As users might prefer different settings of pre/post-processing, this will be helpful for reproducibility of Aydin results.
=> GUI: Saving processing related details

aydin/cli/cli.py, aydin/restoration/denoise/base.py
This PR fixes the problem with Aydin CLI and makes it saves model by default  when use-model flag is not in use.
=> BUG: Aydin CLI was not saving model

CONTRIBUTING.md
This PR brings mention to our own logging system and fixes a typo regarding license we use.
=> DOC: Contributing guideline update

requirements/development.txt
This PR upgrades pyinstaller dependency to 4.8. Version 4.4 was causing import error related to `pkgutil` hook.
=> pyinstaller version upgraded

CONTRIBUTING.md, aydin/gui/_qt/job_runners/denoise_job_runner.py, aydin/gui/tabs/data_model.py, aydin/gui/tabs/qt/images.py
This PR is adding a column on the images tab to expose the output path that will be used to write the resulting denoised image. This feature is requested by @li-li-github first but I think will be helpful to many. Initial design of the idea can be seen in the screenshot here:
One thing worth to mention, it is common to have users want to output everything into one specific folder location. We should try to enable an easy way to just set one output folder as well.
=> GUI: editable output paths

aydin/gui/_qt/job_runners/denoise_job_runner.py, aydin/gui/main_page.py, aydin/gui/tabs/data_model.py, aydin/gui/tabs/qt/images.py
This PR is an attempt to clean the data model from `train_on` field and its related pieces. We do not have `train_on` field on the Aydin Studio for quite some time and this field in the model became redundant.
=> GUI: Removing train_on field from data model

docs/requirements-docs.txt, docs/source/conf.py
This PR adds `sphinx-copybutton` as a dependency and enables a copy button next to the code pieces in our docs. Quite neat.
=> DOC: sphinx-copybuton

setup.cfg
This PR fixes scipy version to `1.7.3` for now as some of the endpoints not supported anymore in the latest version as expressed in #99 .
=> Scipy version fix

aydin/gui/_qt/custom_widgets/denoise_tab_pretrained_method.py, aydin/gui/gui.py, aydin/gui/main_page.py, aydin/gui/tabs/qt/denoise.py, aydin/gui/tabs/qt/images.py, aydin/nn/models/torch/test/test_torch_models.py, aydin/nn/models/utils/torch_dataset.py
This PR implements required changes to enable loading/re-using previously trained Aydin models on Aydin Studio. Currently, it is possible to re-use previously trained models on Aydin CLI and Aydin API. This PR implements basically the same behavior on Aydin Studio.
=> GUI: Load pretrained models

aydin/regression/lgbm.py
With recent updates on our lgbm dependency, we started to fail saving models for lgbm and rf regressors. This patch introduces the needed fix.
=> LGBM save model fix

aydin/it/classic_denoisers/butterworth.py, aydin/it/classic_denoisers/spectral.py
This PR refactors a couple places where we call `** (-0.5)` instead of `1/numpy.sqrt`. For reasoning see this: https://github.com/numpy/numpy/issues/9363
=> numpy sqrt refactor

aydin/it/fgr.py, aydin/restoration/denoise/noise2selffgr.py
This PR fixes the blind_spots argument duplication bug.
I set the blind spot argument to auto by default on fgr level as we were trying to achieve same before on restoration level and prevented duplicating keyword this way
=> FGR blind_spots argumet duplication fix

aydin/gui/_qt/custom_widgets/constructor_arguments.py
This PR enables line wrapping for parameter names on processing and denoising tabs.
=> GUI: Text wrapping for parameter names

aydin/cli/cli.py, aydin/gui/_qt/job_runners/denoise_job_runner.py, aydin/io/utils.py
This PR addresses an existing bug in cli hyperstack command and introduces parameter validation in various places to prevent such bug to occur somewhere else in the codebase
=> BUG: CLI hyperstack command file output

build/linux/hooks/hook-scipy.py, build/osx/hooks/hook-scipy.py, build/win/hooks/hook-scipy.py
This PR addresses the bug occurred in our build pipelines after adding new `scipy` API calls to our codebase.
=> BUG: Build scipy missing hooks

aydin/gui/_qt/custom_widgets/program_flow_diagram.py
This PR removes the remaining pyqt5 imports that we forgot while switching to qtpy.
=> GUI: Removing pyqt5 imports

aydin/gui/_qt/custom_widgets/activity_widget.py, aydin/gui/_qt/custom_widgets/constructor_arguments.py, aydin/gui/_qt/custom_widgets/denoise_tab_method.py, aydin/gui/_qt/custom_widgets/denoise_tab_pretrained_method.py, aydin/gui/_qt/custom_widgets/horizontal_line_break_widget.py, aydin/gui/_qt/custom_widgets/program_flow_diagram.py, aydin/gui/_qt/custom_widgets/qt_range_slider.py, aydin/gui/_qt/custom_widgets/qt_range_slider_with_labels.py, aydin/gui/_qt/custom_widgets/vertical_line_break_widget.py, aydin/gui/_qt/job_runners/denoise_job_runner.py, aydin/gui/_qt/job_runners/preview_job_runner.py, aydin/gui/_qt/job_runners/previewall_job_runner.py, aydin/gui/gui.py, aydin/gui/main_page.py, aydin/gui/tabs/qt/base_cropping.py, aydin/gui/tabs/qt/dimensions.py, aydin/gui/tabs/qt/files.py, aydin/gui/tabs/qt/images.py, aydin/gui/tabs/qt/summary.py, aydin/gui/tabs/qt/training_cropping.py
This PR addresses the all gui related derived class super miscalls. In many occasions we were trying  to get  the super of the extended class instead of the super of the class of interest itself.
=> GUI: Super class call bug fix

setup.cfg
This PR bumps the numexpr version to 2.8.1
=> DEP: numexpr version to 2.8.1

aydin/cli/cli.py
This PR fixes a couple string typos occured in CLI psnr command.
=> CLI: psnr command typo fixes

aydin/cli/cli.py
This PR introduces CLI mse(mean squared error) command which uses `skimage.metrics.mean_squared_error`.
=> CLI: mse command

docs/source/index.rst, docs/source/use_cases/confocal.rst, docs/source/use_cases/confocal_maitre.rst, docs/source/use_cases/confocal_royer.rst, docs/source/use_cases/introduction.rst, docs/source/use_cases/newyork.rst, docs/source/use_cases/opencell.rst
This PR applies some updates to use cases section of our docs. Mainly renaming the titles and splitting the confocal use-case into two and adding new york image use case.
=> DOC: Use case updates

.github/workflows/test_pull_requests.yml, setup.cfg
We are indirectly depending on `protobuf` and with their latest version we started to observe a couple import issues, resolution for now seems to be fixing the protobuf version to a recent but an earlier version. This PR does this.
=> BUG: Latest protobuf import error resolution

docs/source/index.rst, docs/source/use_cases/introduction.rst, docs/source/use_cases/pourquie.rst
This PR introduces the `Chicken Embryos LSM 780 Images from the Pourquie lab (Harvard, Boston)` use case to our documentation.
=> DOC: Chicken embryo use case

aydin/it/cnn.py, aydin/it/test/test_cnn.py, aydin/nn/models/utils/unet_patch_size.py
Currently, default patch_size value is `64` and the mechanism to determine ideal patch_size is not get executed unless you intentionally pass None to `patch_size` argument. This PR basically changes the default `patch_size` value to None and factors out certain code pieces into more modular methods.
=> IT-CNN default patch_size value

aydin/cli/cli.py
This PR adds the  cli command `split_channels` which comes handy when processing multichannel images sometimes.
=> CLI: Split channels

setup.cfg
This PR changes the napari dependency version to 0.4.15 for better compatibility with existing napari plugins in the ecosystem.
=> napari version bump to 0.4.15

aydin/cli/cli.py, aydin/restoration/denoise/classic.py, aydin/restoration/denoise/noise2selfcnn.py, aydin/restoration/denoise/noise2selffgr.py, aydin/restoration/denoise/test/test_n2s_fgr.py
~This PR continues removing the variant option from restoration submodule.~
Edit: Instead of ditching the variant option I will try to refactor the code here to make it work again with all variant/lower_level_args/default selections.
=> Restoration variant option bug fix and refactor

aydin/cli/test/test_cli.py, setup.cfg
To gain more flexibility on extending Aydin in different ways, we need to make the dependency pinnings more relax. Yet we need the strict pinnings for the bundles. This PR refactors the setup.cfg to comfort both needs while moving forward.
=> Making dependency pinnings bundle only

aydin/gui/tabs/qt/denoise.py
This PR implements  the fix for the bug that was causing refreshes on the denoise tab on GUI. This was basically causing users to lose all their option selections on the denoise tab when they want to change between images.
=> BUG: GUI: denoise tab selection persistence

aydin/nn/models/torch/demo/demo_n2t.py, aydin/nn/models/torch/test/test_torch_linear_scaling_unet.py, aydin/nn/models/torch/torch_linear_scaling_unet.py, aydin/nn/models/torch/torch_unet.py
This PR implements the @li-li-github 's famous channel-wise-linearly-scaling UNet model in torch.
=> Torch Linear Scaling UNet

setup.cfg
This PR removes version pinning for the gdown dependency.
=> Relaxing gdown version

setup.cfg
This PR removes version pinning for memoization dependency.
=> Relaxing memoization version

setup.cfg
This PR removes version pinning for `pynndescent` dependency.
=> Relaxing pynndescent version

aydin/gui/_qt/custom_widgets/program_flow_diagram.py, aydin/io/datasets.py
This PR introduces the drosophile egg chamber data from LimeSeg Test Datasets(https://zenodo.org/record/1472859) as a new example dataset to Aydin Studio per @royerloic and @haesleinhuepf requested. Also this will enable aydin napari plugin to expose this data as an example data together with the plugin.
=> GUI: new egg chamber example dataset

setup.cfg
With the latest version of imageio package we are facing import time errors and for now we can fix our dependency to an earlier release of imageio.
=> imagio version fix

.github/workflows/test_pull_requests.yml, conftest.py
This PR introduces a new github action task which will run the heavy tests only after execution standard test suite.
=> Heavy tests action

setup.cfg
Following NEP29, we are increasing the minimum version requirement for numpy dependency.
=> numpy minimum version updated

aydin/cli/cli.py, aydin/cli/test/test_cli.py, aydin/it/demo/n2s/nn/2D_xybatch.py, aydin/it/test/test_classic.py, aydin/it/test/test_deprecated_cnn.py, aydin/it/test/test_fgr_saveload.py, aydin/regression/test/test_regressors.py, aydin/restoration/denoise/test/test_saveload.py
This PR addresses the misusages of `skimage.metrics.peak_signal_noise_ratio` function which requires the true image as the first parameter as shown in docs: https://scikit-image.org/docs/stable/api/skimage.metrics.html#skimage.metrics.peak_signal_noise_ratio.
=> BUG: PSNR function parameter order fix

aydin/cli/cli.py
This PR implements an option to benchmark_algos CLI command to let users choose to save or not save the resulting denoised images with different algorithms. Since we will need to follow a new output file naming conventions, this PR should only be merged after new naming convention situation is handled in another PR.
=> CLI: Save denoised image option on benchmark_algos command

.github/workflows/test_pull_requests.yml, requirements/development.txt
With introduced style 2023, latest black version requires a huge repo-wide reformatting. To prevent that we are fixing black to latest style 2022 version.
=> MAINT: Black version fixing
